export AWS_BUCKET='njphasite-dev'
export AWS_ACCESS_KEY_ID='AKIAJD4ZCLMOXL35O43Q'
export AWS_SECRET_ACCESS_KEY='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'
export RAILS_ENV='production'
export RACK_ENV='production'
export NEW_RELIC_LICENSE_KEY='349ebee10b9e44e6ddda966400afd2527fae9de0'
