# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
   adapter: postgresql
   encoding: unicode
   database: njpha_site_development
   pool: 5
   host: localhost
   username: maindev
   password: dev

production:
   adapter: postgresql
   encoding: unicode
   database: njpha_site_production
   pool: 5
   host: localhost
   username: rails
   password: Tl0yvr3TzO
